ALTER TABLE transactions ADD COLUMN IF NOT EXISTS tx_hash CHAR(64) UNIQUE;

ALTER TABLE transactions ADD COLUMN IF NOT EXISTS is_private BOOLEAN DEFAULT FALSE;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS category TEXT;
